"use client";

import { useEffect, useRef, useState } from "react";
import mermaid from "mermaid";

// Initialize mermaid library options
mermaid.initialize({
  startOnLoad: false,
  theme: "dark",
  securityLevel: "loose",
  fontFamily: "var(--font-body)",
});

export default function MermaidChart({ code }: { code: string }) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [svg, setSvg] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!code) return;
    
    setLoading(true);
    setError(null);
    setSvg(null);

    const renderChart = async () => {
      try {
        const id = `mermaid-${Math.random().toString(36).substring(2, 9)}`;
        const { svg: renderedSvg } = await mermaid.render(id, code);
        setSvg(renderedSvg);
      } catch (err: any) {
        console.error("Mermaid rendering error:", err);
        setError("Mermaid syntax error. Render failed. Please refine your diagram description.");
        // Clear bad state generated by failed render
        const badNodes = document.querySelectorAll('[id^="dmermaid"]');
        badNodes.forEach(node => node.remove());
      } finally {
        setLoading(false);
      }
    };

    // Delay slightly to ensure elements are mounted and styled
    const timer = setTimeout(renderChart, 100);
    return () => clearTimeout(timer);
  }, [code]);

  return (
    <div className="mermaid-chart-container glass-panel">
      {loading && (
        <div className="chart-loader">
          <span>Compiling diagram canvas...</span>
        </div>
      )}

      {error ? (
        <div className="chart-error">
          <p>{error}</p>
          <pre className="raw-code-fallback">{code}</pre>
        </div>
      ) : (
        svg && (
          <div 
            ref={containerRef} 
            className="mermaid-rendered-svg"
            dangerouslySetInnerHTML={{ __html: svg }} 
          />
        )
      )}

      <style jsx>{`
        .mermaid-chart-container {
          width: 100%;
          height: 100%;
          min-height: 400px;
          display: flex;
          align-items: center;
          justify-content: center;
          padding: 24px;
          overflow: auto;
          position: relative;
          background: rgba(17, 24, 39, 0.45);
        }
        .chart-loader {
          color: var(--text-secondary);
          font-size: 0.82rem;
          font-family: var(--font-display);
        }
        .chart-error {
          display: flex;
          flex-direction: column;
          gap: 16px;
          color: var(--accent-danger);
          font-size: 0.85rem;
          max-width: 500px;
          text-align: center;
          width: 100%;
        }
        .raw-code-fallback {
          background: rgba(0, 0, 0, 0.4);
          border: 1px solid rgba(239, 68, 68, 0.2);
          padding: 12px;
          border-radius: 8px;
          text-align: left;
          font-family: monospace;
          font-size: 0.75rem;
          overflow-x: auto;
          color: var(--text-secondary);
        }
        .mermaid-rendered-svg {
          width: 100%;
          height: 100%;
          display: flex;
          justify-content: center;
          align-items: center;
        }
        /* Style adjustments for injected SVG */
        .mermaid-rendered-svg :global(svg) {
          max-width: 100%;
          height: auto;
        }
      `}</style>
    </div>
  );
}
